FROM mcr.microsoft.com/dotnet/sdk AS build

WORKDIR generator
ADD ./Generator ./

RUN dotnet restore

RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/aspnet AS runtime

WORKDIR out
COPY --from=build generator/out ./

ENTRYPOINT ["dotnet", "Generator.dll"]
