FROM mcr.microsoft.com/dotnet/sdk AS build

WORKDIR generator
ADD ./ ./

RUN dotnet restore

RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime

WORKDIR out
COPY --from=build generator/out ./
ENTRYPOINT ["dotnet", "generator.dll"]
