FROM mcr.microsoft.com/dotnet/sdk AS build

WORKDIR GUI
ADD ./ ./

RUN dotnet restore

RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime

WORKDIR out
COPY --from=build GUI/out ./
ENTRYPOINT ["dotnet", "GUI.dll"]
