FROM mcr.microsoft.com/dotnet/sdk AS build

WORKDIR database-server
ADD ./ ./

RUN dotnet restore

RUN dotnet publish -c Release -o out


FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime

WORKDIR out
COPY --from=build database-server/out ./
ENTRYPOINT ["dotnet", "database-server.dll"]
